[package]
name = "amber"
version = "0.3.1-alpha"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heraclitus-compiler = "1.5.8"
similar-string = "1.4.2"
colored = "2.0.0"
itertools = "0.11.0"
clap = { version = "4.4.18", features = ["derive"] }
tempfile = "3.10.1"

[profile.release]
debug = true
