name: Release Linux ARM

on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev

      - name: Install cross
        run: cargo install cross

      - name: Build with cross
        run: cross build --release --target aarch64-unknown-linux-gnu

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: amber-aarch64-unknown-linux-gnu
          path: target/aarch64-unknown-linux-gnu/release/amber

      - name: Get Release Upload URL
        id: get_release
        run: |
          # Fetch the latest release details
          response=$(curl -sL https://api.github.com/repos/${{ github.repository }}/releases/latest)
          # Extract the upload_url template (without the "{?name,label}" suffix)
          upload_url=$(echo $response | jq -r '.upload_url' | sed -e "s/{?name,label}//")
          echo "UPLOAD_URL=$upload_url" >> $GITHUB_ENV

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: target/aarch64-unknown-linux-gnu/release/amber
          asset_name: amber-aarch64.zip
          asset_content_type: application/octet-stream
